# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = ./SimulationFinal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = ./SimulationFinal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start ./SimulationFinal/CMakeFiles ./SimulationFinal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start ./SimulationFinal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SIM

# Build rule for target.
SIM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SIM
.PHONY : SIM

# fast build rule for target.
SIM/fast:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/build
.PHONY : SIM/fast

ArrivalObject.o: ArrivalObject.cpp.o

.PHONY : ArrivalObject.o

# target to build an object file
ArrivalObject.cpp.o:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/ArrivalObject.cpp.o
.PHONY : ArrivalObject.cpp.o

ArrivalObject.i: ArrivalObject.cpp.i

.PHONY : ArrivalObject.i

# target to preprocess a source file
ArrivalObject.cpp.i:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/ArrivalObject.cpp.i
.PHONY : ArrivalObject.cpp.i

ArrivalObject.s: ArrivalObject.cpp.s

.PHONY : ArrivalObject.s

# target to generate assembly for a file
ArrivalObject.cpp.s:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/ArrivalObject.cpp.s
.PHONY : ArrivalObject.cpp.s

Event.o: Event.cpp.o

.PHONY : Event.o

# target to build an object file
Event.cpp.o:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/Event.cpp.o
.PHONY : Event.cpp.o

Event.i: Event.cpp.i

.PHONY : Event.i

# target to preprocess a source file
Event.cpp.i:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/Event.cpp.i
.PHONY : Event.cpp.i

Event.s: Event.cpp.s

.PHONY : Event.s

# target to generate assembly for a file
Event.cpp.s:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/Event.cpp.s
.PHONY : Event.cpp.s

Random.o: Random.cpp.o

.PHONY : Random.o

# target to build an object file
Random.cpp.o:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/Random.cpp.o
.PHONY : Random.cpp.o

Random.i: Random.cpp.i

.PHONY : Random.i

# target to preprocess a source file
Random.cpp.i:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/Random.cpp.i
.PHONY : Random.cpp.i

Random.s: Random.cpp.s

.PHONY : Random.s

# target to generate assembly for a file
Random.cpp.s:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/Random.cpp.s
.PHONY : Random.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SIM.dir/build.make CMakeFiles/SIM.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SIM"
	@echo "... ArrivalObject.o"
	@echo "... ArrivalObject.i"
	@echo "... ArrivalObject.s"
	@echo "... Event.o"
	@echo "... Event.i"
	@echo "... Event.s"
	@echo "... Random.o"
	@echo "... Random.i"
	@echo "... Random.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

